<?php
// Services Data - Extracted from functions.php
// This file contains only the services array without WordPress dependencies

$available_services =  [
    ['name' => 'chiropractic', 'description' => 'Professional chiropractic care for spinal health and alignment'],
    ['name' => 'holistic health', 'description' => 'Comprehensive approach to wellness treating the whole person'],
    ['name' => 'alternative medicine', 'description' => 'Natural healing methods and non-conventional treatments'],
    ['name' => 'massage', 'description' => 'Therapeutic massage therapy for muscle tension and relaxation'],
    ['name' => 'headache', 'description' => 'Specialized treatment for chronic and acute headache relief'],
    ['name' => 'migraine', 'description' => 'Expert care for migraine prevention and management'],
    ['name' => 'neck pain', 'description' => 'Targeted treatment for neck pain and stiffness'],
    ['name' => 'orthotics', 'description' => 'Custom orthotic devices for foot and gait correction'],
    ['name' => 'sports injuries', 'description' => 'Specialized care for athletic injuries and performance recovery'],
    ['name' => 'shoulder pain', 'description' => 'Treatment for shoulder injuries and mobility issues'],
    ['name' => 'elbow pain', 'description' => 'Care for tennis elbow, golfer\'s elbow, and other conditions'],
    ['name' => 'knee pain', 'description' => 'Comprehensive knee injury treatment and rehabilitation'],
    ['name' => 'hip pain', 'description' => 'Hip joint therapy and pain management solutions'],
    ['name' => 'foot pain', 'description' => 'Treatment for plantar fasciitis and other foot conditions'],
    ['name' => 'hand pain', 'description' => 'Care for carpal tunnel, arthritis, and hand injuries'],
    ['name' => 'wrist pain', 'description' => 'Treatment for repetitive strain and wrist injuries'],
    ['name' => 'ankle pain', 'description' => 'Ankle sprain recovery and chronic pain management'],
    ['name' => 'nutrition', 'description' => 'Personalized nutrition counseling and dietary planning'],
    ['name' => 'gold standard supplements', 'description' => 'High-quality nutritional supplements and vitamins'],
    ['name' => 'acupuncture', 'description' => 'Traditional Chinese medicine acupuncture treatments'],
    ['name' => 'wellness', 'description' => 'Comprehensive wellness programs for optimal health'],
    ['name' => 'pain management', 'description' => 'Multi-modal approach to chronic pain relief'],
    ['name' => 'sports medicine', 'description' => 'Athletic performance optimization and injury prevention'],
    ['name' => 'rehabilitation', 'description' => 'Physical rehabilitation and recovery programs'],
    ['name' => 'car accidents', 'description' => 'Specialized care for auto accident injuries and recovery'],
    ['name' => 'back pain', 'description' => 'Comprehensive back pain treatment and spinal care'],
    ['name' => 'head pain', 'description' => 'Treatment for various types of head and facial pain'],
    ['name' => 'safe weight', 'description' => 'Safe and effective weight management programs'],
    ['name' => 'weight loss products', 'description' => 'Professional-grade weight loss supplements and tools'],
    ['name' => 'weight issues', 'description' => 'Comprehensive approach to weight-related health concerns'],
    ['name' => 'weight management', 'description' => 'Long-term weight maintenance and lifestyle coaching'],
    ['name' => 'weight loss', 'description' => 'Medically supervised weight loss programs'],
    ['name' => 'herniated disc', 'description' => 'Non-surgical treatment for disc herniation and bulging'],
    ['name' => 'osteoporosis', 'description' => 'Bone density improvement and fracture prevention'],
    ['name' => 'personal injury', 'description' => 'Recovery care for personal injury cases'],
    ['name' => 'arthritis', 'description' => 'Joint pain relief and arthritis management'],
    ['name' => 'accidents', 'description' => 'Comprehensive care for accident-related injuries'],
    ['name' => 'concussion', 'description' => 'Specialized concussion treatment and recovery protocols'],
    ['name' => 'traumatic brain injury', 'description' => 'Expert care for TBI recovery and rehabilitation'],
    ['name' => 'TBI', 'description' => 'Traumatic brain injury treatment and support'],
    ['name' => 'whiplash', 'description' => 'Whiplash injury treatment and neck rehabilitation'],
    ['name' => 'lower back pain', 'description' => 'Targeted treatment for lumbar spine conditions'],
    ['name' => 'upper back pain', 'description' => 'Thoracic spine care and upper back relief'],
    ['name' => 'injuries', 'description' => 'General injury treatment and recovery services'],
    ['name' => 'middle back pain', 'description' => 'Mid-thoracic spine treatment and pain relief']
];
?>
